<#include "header.ftlh">

<div class="wrap">
    <div class="container">


        <div class="jumbotron jumbotron-fluid text-center"
             style="background-color: rgba(163, 177, 179, 0.7); margin-bottom: 200px">
            <div class="container">
                <h1 class="display-4">Logged out</h1>
                <p class="lead">Thank you. <a href="/start">Log in again</a></p>
            </div>
        </div>

    </div>
</div>

<#include "footer.ftlh">