<#include "manager-header.ftlh">
<div class="wrap-admin">
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-8">

                    <div class="alert alert-success" role="alert">
                        The account has been deleted. <a href="students-list">Show list of students</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
<#include "manager-footer.ftlh">