<#include "manager-header.ftlh">
<div class="wrap-admin">
    <div class="container">

        <div class="jumbotron">
            <h1 class="display-4">Your Menu</h1>
            <hr class="my-4">
            <div class="row">
                <div class="col-12">

                    <div class="row">
                        <div class="col-sm-6 padding">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">Setting</h5>
                                    <h1>⚙️</h1>
                                    <p class="card-text"></p>
                                    <a href="/" class="btn btn-primary">Go setting</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 padding">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">Manager</h5>
                                    <p class="card-text">Manage accounts Managers</p>
                                    <a href="/managers-list" class="btn btn-primary">Go Managers</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 padding">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">Instructors</h5>
                                    <p class="card-text">Manage accounts Instructors</p>
                                    <a href="/instructors-list" class="btn btn-primary">Go Instructors</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 padding">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">Students</h5>
                                    <p class="card-text">Manage accounts Students</p>
                                    <a href="/students-list" class="btn btn-primary">Go Students</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 padding">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">Courses</h5>
                                    <p class="card-text">Manage Courses</p>
                                    <a href="/courses-list" class="btn btn-primary">Go Courses</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>


    </div>

</div>


<#include "manager-footer.ftlh">